name: Build and Release (Self-hosted)

on:
    push:
      tags:
        - '*'

jobs:
  build:
    name: Build Images
    permissions: write-all
    runs-on: bubbles
    outputs:
      regular_build: ${{ steps.regular_build.outputs.success }}
    
    steps:
      - name: Install / update .NET SDK
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && chmod +x dotnet-install.sh && ./dotnet-install.sh --channel 10.0
          rm dotnet-install.sh

      - name: Update repository
        working-directory: /home/bubbles/TKMM-NX
        run: |
          git fetch --all --tags -f
          git checkout ${{ github.ref_name }} -f
          
      - name: Build regular image
        id: regular_build
        working-directory: /home/bubbles/TKMM-NX
        run: |
          export PATH="/home/bubbles/.dotnet:$PATH"
          TKMM_VERSION="${{ github.ref_name }}"
          TKMM_VERSION="${TKMM_VERSION%%-rev-nx*}"
          rm -rf release && mkdir -p release
          rm -rf target/*
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean tkmm
          # DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean samba
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean linux
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean busybox
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean initramfs
          THREADCOUNT=20 DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 TKMM_VERSION="$TKMM_VERSION" make image
          mv target/* release/
          echo "success=true" >> $GITHUB_OUTPUT

      - name: Build debug image
        id: debug_build
        working-directory: /home/bubbles/TKMM-NX
        continue-on-error: true
        run: |
          export PATH="/home/bubbles/.dotnet:$PATH"
          TKMM_VERSION="${{ github.ref_name }}"
          TKMM_VERSION="${TKMM_VERSION%%-rev-nx*}"
          rm -rf debug && mkdir -p debug
          THREADCOUNT=20 DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 DEVMODE=enabled TKMM_VERSION="$TKMM_VERSION" make image
          mv target/* debug/

  release:
    needs: build
    if: needs.build.outputs.regular_build == 'true'
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      release: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: TKMM-NX - ${{ github.ref_name }}
          draft: false
          prerelease: false

  upload:
    name: Upload Images
    needs: [build, release]
    permissions: write-all
    runs-on: bubbles
    
    steps:
      - name: Prepare release assets
        working-directory: /home/bubbles/TKMM-NX
        run: |
          mkdir -p github-release
          cp release/*.zip github-release/tkmm-nx.zip
          cp release/update.tar github-release/update.tar

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/bubbles/TKMM-NX/github-release/tkmm-nx.zip
            /home/bubbles/TKMM-NX/github-release/update.tar

      - name: Upload images to mirror
        working-directory: /home/bubbles/TKMM-NX
        run: |
          scp -i ~/.ssh/github_runner_sftp_key release/* ubuntu@repo.tkmm.org:/var/www/html/repo/.tkmm-nx/Releases
          scp -i ~/.ssh/github_runner_sftp_key debug/* ubuntu@repo.tkmm.org:/var/www/html/repo/.tkmm-nx/Debug

      - name: Cleanup Folders
        run: |
          rm -rf /home/bubbles/TKMM-NX/github-release
          rm -rf /home/bubbles/TKMM-NX/release
          rm -rf /home/bubbles/TKMM-NX/debug